## Problem Statement

E-commerce platforms generate large amounts of customer behavioral and
transaction-related data. Identifying customers who are likely to churn can
help businesses understand customer behavior and support data-driven
customer retention strategies.

The objective of this project is to analyze customer data and develop a
machine learning classification model that predicts whether a customer is
likely to churn based on their available behavioral and demographic
characteristics.

## Project Objectives

1. Analyze e-commerce customer behavior using data analytics techniques.
2. Understand the factors associated with customer churn.
3. Clean and preprocess the dataset.
4. Perform exploratory data analysis.
5. Engineer meaningful features for machine learning.
6. Develop classification models for churn prediction.
7. Evaluate the models using appropriate classification metrics.
8. Save the trained machine learning pipeline.
9. Deploy the model using Flask.
10. Provide individual and batch customer churn prediction.

In [1]:
import pandas as pd
import numpy as np

# Dataset path
file_path = "../data/raw/data_ecommerce_customer_churn.csv"

# Load the dataset
df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

df.head()

Dataset loaded successfully!
Dataset shape: (3941, 11)

,Tenure,WarehouseToHome,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,DaySinceLastOrder,CashbackAmount,Churn
0,15.0,29.0,4,Laptop & Accessory,3,Single,2,0,7.0,143.32,0
1,7.0,25.0,4,Mobile,1,Married,2,0,7.0,129.29,0
2,27.0,13.0,3,Laptop & Accessory,1,Married,5,0,7.0,168.54,0
3,20.0,25.0,4,Fashion,3,Divorced,7,0,NaN,230.27,0
4,30.0,15.0,4,Others,4,Single,8,0,8.0,322.17,0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3941 entries, 0 to 3940
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Tenure                    3747 non-null   float64
 1   WarehouseToHome           3772 non-null   float64
 2   NumberOfDeviceRegistered  3941 non-null   int64
 3   PreferedOrderCat          3941 non-null   object
 4   SatisfactionScore         3941 non-null   int64
 5   MaritalStatus             3941 non-null   object
 6   NumberOfAddress           3941 non-null   int64
 7   Complain                  3941 non-null   int64
 8   DaySinceLastOrder         3728 non-null   float64
 9   CashbackAmount            3941 non-null   float64
 10  Churn                     3941 non-null   int64
dtypes: float64(4), int64(5), object(2)
memory usage: 338.8+ KB

In [3]:
print("Dataset Columns:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Dataset Columns:
1. Tenure
2. WarehouseToHome
3. NumberOfDeviceRegistered
4. PreferedOrderCat
5. SatisfactionScore
6. MaritalStatus
7. NumberOfAddress
8. Complain
9. DaySinceLastOrder
10. CashbackAmount
11. Churn

# E-Commerce Customer Churn Prediction Using Machine Learning

### IBM SkillsBuild Data Analytics with AI Internship 2026

**Author:** Deepak Kumar Rajak

---

## Project Overview

Customer churn is an important business problem in the e-commerce industry.
Customers who stop purchasing from an e-commerce platform can negatively
affect revenue and long-term customer relationships.

This project aims to analyze e-commerce customer behavior and develop a
machine learning classification system to predict whether a customer is
likely to churn.

The project follows an end-to-end machine learning workflow including:

- Data understanding
- Data cleaning and preprocessing
- Exploratory data analysis
- Feature engineering
- Machine learning model development
- Model evaluation
- Model persistence
- Flask-based deployment
- Individual customer prediction
- Batch prediction
- Analytics dashboard

In [ ]:
# Check missing values
missing_values = df.isnull().sum()

print("Missing Values:")
print(missing_values)

Missing Values:
Tenure                      194
WarehouseToHome             169
NumberOfDeviceRegistered      0
PreferedOrderCat              0
SatisfactionScore             0
MaritalStatus                 0
NumberOfAddress               0
Complain                      0
DaySinceLastOrder           213
CashbackAmount                0
Churn                         0
dtype: int64

In [5]:
# Display only columns containing missing values
missing_summary = df.isnull().sum()
missing_summary = missing_summary[missing_summary > 0]

print("Columns with missing values:")
print(missing_summary)

Columns with missing values:
Tenure               194
WarehouseToHome      169
DaySinceLastOrder    213
dtype: int64

In [6]:
# Check duplicate records
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 671

In [7]:
# Check target distribution
churn_counts = df["Churn"].value_counts()

print("Churn Distribution:")
print(churn_counts)

Churn Distribution:
Churn
0    3267
1     674
Name: count, dtype: int64

In [8]:
# Check target percentage
churn_percentage = df["Churn"].value_counts(normalize=True) * 100

print("Churn Percentage:")
print(churn_percentage.round(2))

Churn Percentage:
Churn
0    82.9
1    17.1
Name: proportion, dtype: float64

In [9]:
# Check number of unique values in each column
print("Unique values in each column:")
print(df.nunique())

Unique values in each column:
Tenure                        36
WarehouseToHome               33
NumberOfDeviceRegistered       6
PreferedOrderCat               6
SatisfactionScore              5
MaritalStatus                  3
NumberOfAddress               14
Complain                       2
DaySinceLastOrder             22
CashbackAmount              2335
Churn                          2
dtype: int64

In [11]:
for column in df.columns:
    print(repr(column))

'Tenure'
'WarehouseToHome'
'NumberOfDeviceRegistered'
'PreferedOrderCat'
'SatisfactionScore'
'MaritalStatus'
'NumberOfAddress'
'Complain'
'DaySinceLastOrder'
'CashbackAmount'
'Churn'

In [2]:
print("DataFrame shape:", df.shape)
print("Columns:", df.columns.tolist())
print("DataFrame type:", type(df))

DataFrame shape: (3941, 11)
Columns: ['Tenure', 'WarehouseToHome', 'NumberOfDeviceRegistered', 'PreferedOrderCat', 'SatisfactionScore', 'MaritalStatus', 'NumberOfAddress', 'Complain', 'DaySinceLastOrder', 'CashbackAmount', 'Churn']
DataFrame type: <class 'pandas.core.frame.DataFrame'>

In [5]:
# Clean column names
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['Tenure', 'WarehouseToHome', 'NumberOfDeviceRegistered', 'PreferedOrderCat', 'SatisfactionScore', 'MaritalStatus', 'NumberOfAddress', 'Complain', 'DaySinceLastOrder', 'CashbackAmount', 'Churn']

In [7]:
import pandas as pd

# Reload the dataset from scratch
df = pd.read_csv("../data/raw/data_ecommerce_customer_churn.csv")

print("Shape:", df.shape)

print("\nExact columns:")
for col in df.columns:
    print(repr(col))

print("\nFourth column values:")
print(df.iloc[:, 3].value_counts())

Shape: (3941, 11)

Exact columns:
'Tenure'
'WarehouseToHome'
'NumberOfDeviceRegistered'
'PreferedOrderCat'
'SatisfactionScore'
'MaritalStatus'
'NumberOfAddress'
'Complain'
'DaySinceLastOrder'
'CashbackAmount'
'Churn'

Fourth column values:
PreferedOrderCat
Laptop & Accessory    1458
Mobile Phone           887
Fashion                585
Mobile                 559
Grocery                273
Others                 179
Name: count, dtype: int64

In [8]:
# Standardize column names
df.columns = df.columns.str.strip()

print("Cleaned column names:")
print(df.columns.tolist())

Cleaned column names:
['Tenure', 'WarehouseToHome', 'NumberOfDeviceRegistered', 'PreferedOrderCat', 'SatisfactionScore', 'MaritalStatus', 'NumberOfAddress', 'Complain', 'DaySinceLastOrder', 'CashbackAmount', 'Churn']

In [9]:
# Get categorical column names directly from the dataframe
preferred_order_col = df.columns[3]
marital_status_col = df.columns[5]

print("Preferred Order Categories:")
print(df[preferred_order_col].value_counts())

print("\nMarital Status:")
print(df[marital_status_col].value_counts())

Preferred Order Categories:
PreferedOrderCat
Laptop & Accessory    1458
Mobile Phone           887
Fashion                585
Mobile                 559
Grocery                273
Others                 179
Name: count, dtype: int64

Marital Status:
MaritalStatus
Married     2055
Single      1310
Divorced     576
Name: count, dtype: int64

In [10]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Tenure                      194
WarehouseToHome             169
NumberOfDeviceRegistered      0
PreferedOrderCat              0
SatisfactionScore             0
MaritalStatus                 0
NumberOfAddress               0
Complain                      0
DaySinceLastOrder           213
CashbackAmount                0
Churn                         0
dtype: int64

In [11]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 671

In [12]:
print("Churn Distribution:")
print(df["Churn"].value_counts())

print("\nChurn Percentage:")
print((df["Churn"].value_counts(normalize=True) * 100).round(2))

Churn Distribution:
Churn
0    3267
1     674
Name: count, dtype: int64

Churn Percentage:
Churn
0    82.9
1    17.1
Name: proportion, dtype: float64

In [13]:
print("Unique values in each column:")
print(df.nunique())

Unique values in each column:
Tenure                        36
WarehouseToHome               33
NumberOfDeviceRegistered       6
PreferedOrderCat               6
SatisfactionScore              5
MaritalStatus                  3
NumberOfAddress               14
Complain                       2
DaySinceLastOrder             22
CashbackAmount              2335
Churn                          2
dtype: int64

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Tenure,3747.0,10.081398,8.498864,0.0,2.0,9.00,16.00,61.00
WarehouseToHome,3772.0,15.650583,8.452301,5.0,9.0,14.00,21.00,127.00
NumberOfDeviceRegistered,3941.0,3.679269,1.013938,1.0,3.0,4.00,4.00,6.00
SatisfactionScore,3941.0,3.088302,1.381832,1.0,2.0,3.00,4.00,5.00
NumberOfAddress,3941.0,4.237757,2.626699,1.0,2.0,3.00,6.00,22.00
Complain,3941.0,0.282416,0.450232,0.0,0.0,0.00,1.00,1.00
DaySinceLastOrder,3728.0,4.531652,3.667648,0.0,2.0,3.00,7.00,46.00
CashbackAmount,3941.0,176.707419,48.791784,0.0,145.7,163.34,195.25,324.99
Churn,3941.0,0.171023,0.376576,0.0,0.0,0.00,0.00,1.00